[workspace]
authors = ["nihildigit <nihildigit@outlook.com>"]
channels = ["conda-forge"]
name = "prcv"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "13.0"

[dependencies]
python = "3.12.*"
pytorch-gpu = "2.9.*"
torchvision = "0.24.*"
matplotlib = ">=3.10.8,<4"
scienceplots = ">=2.2.0,<3"
tqdm = ">=4.67.1,<5"
pyyaml = ">=6.0.3,<7"
pandas = ">=2.3.3,<3"
pillow = ">=12.0.0,<13"
opencv = ">=4.12.0,<5"
tensorboard = ">=2.20.0,<3"

[pypi-dependencies]
cityscapesscripts = ">=2.2.4, <3"

